import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {pages} from '../src/pages.mjs';
import {catalog} from '../src/catalog.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const write=(p,s)=>{fs.mkdirSync(path.dirname(path.join(root,p)),{recursive:true});fs.writeFileSync(path.join(root,p),s);};
const registry=JSON.parse(fs.readFileSync(path.join(root,'design/presentation.yaml'),'utf8'));
write('design-system/tokens.css','/* Generated from design/presentation.yaml. Do not edit. */\n:root {\n'+registry.variables.map(v=>`  ${v.projections.css.customProperty}: ${v.values.base};`).join('\n')+'\n}\n');
for(const name of ['system.css','interactions.js'])write('design-system/'+name,fs.readFileSync(path.join(root,'src',name),'utf8'));
for(const [name,html] of Object.entries(pages))write('templates/'+name,html);
write('design-system/index.html',catalog());
write('design-system/catalog.css',fs.readFileSync(path.join(root,'src/catalog.css'),'utf8'));
write('design/template-manifest.json',JSON.stringify({stage:'prototype',generatedBy:'scripts/build.mjs',pages:Object.keys(pages).map(path=>({path:'templates/'+path}))},null,2)+'\n');
console.log(`Built ${Object.keys(pages).length} template examples and the design-system catalog.`);
