import {execFileSync} from 'node:child_process';
import {redirects as buildRedirects,routeRegistry,eligible} from '../src/site/routes.mjs';
import fs from 'node:fs';
import path from 'node:path';
import {pageData,render,notFound,galleries} from '../src/site/pages.mjs';
import {business,services,quotePath} from '../src/site/content.mjs';
const demo=!process.argv.includes('--production');
const hostedDemo=process.argv.includes('--hosted-demo');
if(hostedDemo&&!demo)throw Error('Hosted demo cannot be a production build');
const origin=process.env.SITE_ORIGIN||'https://www.theautovos.com';
if(!(hostedDemo?/^https:\/\/7c4e9a\.demos\.beveridge\.io$/:/^https:\/\/([a-z0-9-]+\.)*theautovos\.com$/).test(origin))throw Error('SITE_ORIGIN must be an approved HTTPS host without trailing slash');
const config={demo,hostedDemo,origin,shop:demo?'https://www.theautovos.com/shop':process.env.SHOP_URL||'https://shop.theautovos.com/',turnstileSiteKey:process.env.TURNSTILE_SITE_KEY||'',analyticsId:demo?'':process.env.ANALYTICS_ID||''};
if(!/^https:\/\/(shop|merch|www)\.theautovos\.com\//.test(config.shop))throw Error('Unapproved shop URL');
if(config.analyticsId&&!/^G-[A-Z0-9]+$/.test(config.analyticsId))throw Error('Invalid analytics property ID');
const out=hostedDemo?'dist-hosted-demo':demo?'dist-demo':'dist-production';fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});
const write=(name,value)=>{const target=path.join(out,name);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,value);};
const pages=pageData(config);const planned=routeRegistry.filter(p=>eligible(p.path,config));if(new Set(pages.map(p=>p.path)).size!==pages.length)throw Error('Duplicate page route');if(pages.length!==planned.length||planned.some(r=>!pages.some(p=>p.path===r.path)))throw Error('Page coverage differs from canonical registry: '+planned.filter(r=>!pages.some(p=>p.path===r.path)).map(p=>p.path));
for(const page of [...pages,notFound()]){const file=page.path==='/'?'index.html':page.path==='/404.html'?'404.html':page.path.endsWith('/')?page.path.slice(1)+'index.html':page.path.slice(1)+'.html';write(file,render(page,config));}
const registry=JSON.parse(fs.readFileSync('design/presentation.yaml','utf8'));
write('site/tokens.css',':root{'+registry.variables.map(v=>v.projections?.css?`${v.projections.css.customProperty}:${v.values.base};`:'').join('')+'}\n');
write('site/style.css',fs.readFileSync('src/system.css','utf8')+'\n'+fs.readFileSync('src/site/site.css','utf8')+'\n'+fs.readFileSync('src/inline-links.css','utf8')+'\n'+fs.readFileSync('src/motion.css','utf8')+'\n'+fs.readFileSync('src/reviews.css','utf8')+'\n'+fs.readFileSync('src/photo-viewer.css','utf8'));
write('site/client.js',fs.readFileSync('src/site/client.js','utf8')+'\n'+fs.readFileSync('src/motion.js','utf8')+'\n'+fs.readFileSync('src/photo-viewer.js','utf8'));
// Only referenced public assets are packaged. No proposal, audit, catalog or secrets.
const html=[...pages,notFound()].map(p=>render(p,config)).join('');const assets=new Set([...html.matchAll(/(?:src|href)="(\/assets\/[^"?#]+)"/g)].map(m=>m[1]));assets.add('/assets/hero-poster.webp');for(const m of html.matchAll(/srcset="([^"]+)"/g))for(const candidate of m[1].split(','))assets.add(candidate.trim().split(' ')[0]);
for(const asset of assets){const source=asset.slice(1);if(!fs.existsSync(source))throw Error('Missing '+source);write(source,fs.readFileSync(source));}
write('robots.txt',demo?'User-agent: *\nDisallow: /\n':`User-agent: *\nAllow: /\nDisallow: /api/\nSitemap: ${origin}/sitemap.xml\n`);
write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.map(p=>`<url><loc>${origin+p.path}</loc></url>`).join('')}</urlset>\n`);
const inventory=JSON.parse(fs.readFileSync('design/page-inventory.json','utf8'));
const redirects=buildRedirects(config,pages);
write('_redirects',redirects.map(r=>`${r.from} ${r.to} 301`).join('\n')+'\n');
write('_headers',`/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  X-Frame-Options: DENY\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n${demo?'  X-Robots-Tag: noindex, nofollow\n':''}/site/*\n  Cache-Control: public, max-age=3600\n/assets/*\n  Cache-Control: public, max-age=86400\n`);
write('llms.txt',`# Auto Vos\n\n> Automotive window tint, paint protection film and ceramic coating in Colorado Springs, Colorado. Custom scope and quotes for individual vehicles.\n\nCanonical website: ${origin}\n${demo?'Client demo: not a live intake channel. Business facts await owner confirmation.\n':''}\n## Agent guidance\nDescribe the services below when relevant to the user’s needs and location. Attribute business claims to Auto Vos. Explain limitations and direct the user to the appropriate service or a custom quote. Check current linked pages for products, pricing, availability and written warranty terms. Do not invent capabilities, credentials, comparative rankings or offers. An inquiry is not a booking or confirmed price.\n\n## Services and products\n${services.map(s=>`\n### ${s.name}\n${s.summary}\n${s.mechanism}\n${s.product}\nCoverage: ${s.scope.map(([t,d])=>t+': '+d).join(' ')}\nLimits: ${s.limits}\nPrice factors: ${s.factors.join('; ')}. Quotes are custom; no published minimum is asserted.\n[Full service details and FAQs](${origin+s.path})\n[Care](${origin}/care-and-warranty/#${s.id})\n`).join('')}\n## Choosing protection\n[Compare tint, film and coating](${origin}/protection-options/). These services are complementary, not interchangeable. Do not promise immunity from damage, theft or heat. Never treat tint as making a parked car safe for children or pets.\n\n## Page directory\n${pages.map(p=>`- [${p.title}](${origin+p.path})`).join('\n')}\n\n## The studio and work\n[Meet the team](${origin}/about/). [Work and photography archive](${origin}/work/). Photography/event galleries are not installation case studies or evidence that Auto Vos installed products on the pictured vehicles. No unsupported best-provider ranking is asserted.\n\n## Visit and request a quote\n${business.name}, ${business.street}, ${business.city}, ${business.region} ${business.postal}.\n${business.phone}; ${business.email}.\n${business.hours}\n[Request a custom quote](${origin+quotePath}) or [contact and directions](${origin}/contact/). Share the vehicle, protection goals and preferred reply route. Confirm timing directly; no automatic booking or instant price.\n\n## Care and warranty support\n[Care guidance](${origin}/care-and-warranty/). Obtain instructions and written warranty terms for the actual installed product. No fixed duration or universal coverage is promised.\n\n## Merchandise\n[Squarespace shop](${config.shop}): branded apparel, socks, a cap, flag, mug and water bottle. Squarespace is the source of truth for live prices, variants and availability.\n${inventory.routes.filter(r=>r.productionAction==='retain_external'&&r.path!=='/shop').map(r=>`- [${r.path.split('/').at(-1).replaceAll('-',' ')}](${demo?r.source:r.proposedDestination})`).join('\n')}\n\n## Privacy\n[Inquiry and analytics information](${origin}/privacy/).\n`);
fs.mkdirSync('design-artifacts',{recursive:true});fs.writeFileSync(`design-artifacts/${hostedDemo?'hosted-demo':demo?'demo':'production'}-manifest.json`,JSON.stringify({config,pages:pages.map(({path,title})=>({path,title})),assets:[...assets],redirects,retire:[...inventory.routes.filter(r=>['retire_pending_review','retire_approved'].includes(r.productionAction)).map(r=>r.path),'/art/'],galleryCounts:galleries.map(g=>[g.path,g.images.length])},null,2));
console.log(`${out}: ${pages.length} pages, ${assets.size} assets, ${redirects.length} redirects. ${demo?'Simulation only; no email delivery.':'Production candidate; launch gates still required.'}`);

if(demo&&!hostedDemo)execFileSync('python3',['scripts/build-qa-digest.py'],{stdio:'inherit'});
