import fs from 'node:fs';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import {execFileSync,spawn} from 'node:child_process';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE?pathToFileURL(process.env.PLAYWRIGHT_MODULE).href:'playwright');const base='http://127.0.0.1:8792',checks=[];
execFileSync(process.execPath,['scripts/build-site.mjs','--production'],{env:{...process.env,ANALYTICS_ID:'G-TEST123',TURNSTILE_SITE_KEY:'test-only'}});
const server=spawn(process.execPath,['scripts/serve-site.mjs','--production'],{env:{...process.env,PORT:'8792'},stdio:'pipe'});await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);});const browser=await chromium.launch({channel:'chrome',headless:true});
try{const ctx=await browser.newContext();const external=[];await ctx.route('**/*',async r=>{const u=new URL(r.request().url());if(u.origin===base)return r.continue();external.push(u.hostname);return r.fulfill({status:200,contentType:'text/javascript',body:''});});const page=await ctx.newPage();await page.goto(base+'/get-a-quote-auto-vos?utm_source=search&utm_campaign=spring&email=private@example.com');assert(external.every(host=>host==='challenges.cloudflare.com')); await page.getByRole('button',{name:'Allow analytics',exact:true}).click();await page.waitForFunction(()=>window.dataLayer?.length>2);let events=await page.evaluate(()=>window.dataLayer.map(x=>Array.from(x)));assert.equal(events.filter(x=>x[0]==='event'&&x[1]==='page_view').length,1);assert(!JSON.stringify(events).includes('private@example.com'));checks.push('No analytics before consent; clean page URL after consent');
const fill=async()=>{await page.locator('#name').fill('Private Test Name');await page.locator('#email').fill('private@example.com');await page.locator('#service').selectOption('ceramic');await page.locator('#message').fill('PRIVATE MESSAGE CONTENT');await page.locator('#consent').check();};await fill();await page.route('**/api/inquiry',r=>r.fulfill({status:502,contentType:'application/json',body:JSON.stringify({state:'failed',message:'Provider rejected the inquiry.'})}));await page.locator('#send').click();await page.waitForFunction(()=>document.querySelector('#form-status').textContent.includes('rejected'));events=await page.evaluate(()=>window.dataLayer.map(x=>Array.from(x)));assert.equal(events.filter(x=>x[1]==='inquiry_accepted').length,0);checks.push('Failed inquiry is not counted as a lead');await page.unroute('**/api/inquiry');await page.route('**/api/inquiry',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({state:'accepted',id:'synthetic-test',message:'Accepted for delivery.'})}));await page.locator('#send').click();await page.waitForFunction(()=>document.querySelector('#send').textContent==='Inquiry accepted');events=await page.evaluate(()=>window.dataLayer.map(x=>Array.from(x)));assert.equal(events.filter(x=>x[1]==='inquiry_accepted').length,1);assert.equal(events.filter(x=>x[1]==='form_start').length,1);assert(!/Private Test|private@example|PRIVATE MESSAGE/.test(JSON.stringify(events)));checks.push('Accepted inquiry once; no form PII in event payloads');
await page.getByRole('button',{name:'Analytics choices',exact:true}).click();await page.getByRole('button',{name:'No thanks',exact:true}).click();assert.equal(await page.evaluate(()=>window['ga-disable-G-TEST123']),true);checks.push('Consent can be withdrawn');
fs.writeFileSync('design-artifacts/site/measurement-proof.json',JSON.stringify({checks,limits:'Synthetic provider and analytics responses only. No analytics property or inbox contacted.'},null,2));console.log(checks);
}finally{await browser.close();server.kill();execFileSync(process.execPath,['scripts/build-site.mjs','--production']);}
