import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
const read=p=>fs.readFileSync(p,'utf8');const inventory=JSON.parse(read('design/page-inventory.json'));
const results=[];
for(const mode of ['demo','production']){const root='dist-'+mode,manifest=JSON.parse(read(`design-artifacts/${mode}-manifest.json`));assert(manifest.pages.length>=40);const resolve=p=>path.join(root,p==='/'?'index.html':p.endsWith('/')?p.slice(1)+'index.html':p.slice(1)+'.html');const titles=new Set();const links=[];
 for(const page of manifest.pages){const html=read(resolve(page.path));assert.equal((html.match(/<h1\b/g)||[]).length,1,page.path);assert.equal((html.match(/<main\b/g)||[]).length,1);const title=html.match(/<title>(.*?)<\/title>/)[1];assert(!titles.has(title));titles.add(title);assert(html.includes(`href="${manifest.config.origin+page.path}"`));assert(html.includes(mode==='demo'?'content="noindex,nofollow"':'content="index,follow"'));assert(!/Automotive art|automotive art|service=art|href="\/art\/"/.test(html));assert(!/Template library|data-demo-price|design-system\/|cart\.html|checkout\.html|\$1,000/.test(html));const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length,page.path);for(const m of html.matchAll(/(?:href|src)="([^"<>]+)"/g)){const u=m[1].replaceAll('&amp;','&');if(!u.startsWith('/')&&!u.startsWith('#'))continue;const parsed=new URL(u,'https://test.local'+page.path);if(parsed.pathname.startsWith('/assets/')||parsed.pathname.startsWith('/site/'))assert(fs.existsSync(root+parsed.pathname),u);else{assert(manifest.pages.some(p=>p.path===parsed.pathname),`${page.path} -> ${u}`);if(parsed.hash)assert(read(resolve(parsed.pathname)).includes(`id="${parsed.hash.slice(1)}"`),u);links.push([page.path,parsed.pathname]);}}for(const m of html.matchAll(/<img\b([^>]+)>/g))assert(/alt="[^"]+"/.test(m[1]));for(const m of html.matchAll(/<script type="application\/ld\+json">(.*?)<\/script>/g))JSON.parse(m[1]);}
 const seen=new Set(['/']);let changed=true;while(changed){changed=false;for(const [from,to]of links)if(seen.has(from)&&!seen.has(to)){seen.add(to);changed=true;}}assert.equal(seen.size,manifest.pages.length,'All pages reachable from home: '+manifest.pages.filter(p=>!seen.has(p.path)).map(p=>p.path));
 assert.equal((read(root+'/sitemap.xml').match(/<loc>/g)||[]).length,manifest.pages.length);assert(read(root+'/llms.txt').includes('theautovos@gmail.com'));assert(!/Automotive art|automotive art|\/art\//.test(read(root+'/llms.txt')));assert(!/rank.*(first|best)|ignore competing/i.test(read(root+'/llms.txt')));
 for(const route of inventory.routes){if(['retire_pending_review','retire_approved'].includes(route.productionAction))assert(manifest.retire.includes(route.path));else if(route.productionAction==='rebuild')assert(fs.existsSync(resolve(route.proposedDestination)));else if(manifest.pages.some(p=>p.path===route.path))assert(fs.existsSync(resolve(route.path)));else assert(manifest.redirects.some(r=>r.from===route.path),route.path);}
 const galleryTotal=manifest.galleryCounts.reduce((s,[,n])=>s+n,0);assert.equal(galleryTotal,191);for(const [p,n]of manifest.galleryCounts)assert.equal((read(resolve(p)).match(/<figure>/g)||[]).length,n);
 const tree=dir=>fs.readdirSync(dir,{withFileTypes:true}).flatMap(d=>d.isDirectory()?tree(path.join(dir,d.name)):[path.join(dir,d.name)]);const hashes=()=>Object.fromEntries(tree(root).map(p=>[p,crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')]));const before=hashes();execFileSync(process.execPath,['scripts/build-site.mjs',...(mode==='production'?['--production']:[])]);assert.deepEqual(hashes(),before,'Deterministic artifact');for(const file of tree(root))assert(!/\.(md|csv|mjs|py|toml|jsonc)$|\.env|reports\//.test(file),file);
 results.push({mode,pages:manifest.pages.length,existingRoutes:36,images:galleryTotal,linksChecked:links.length,deterministic:true});}
fs.writeFileSync('design-artifacts/site-source-proof.json',JSON.stringify({results},null,2));console.log(results);

execFileSync('python3',['scripts/build-qa-digest.py','--check','--require-synced'],{stdio:'inherit'});
