import {business,services,product} from './content.mjs';
export const escape = value => String(value ?? '').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths = {arrow:'M5 19 19 5M5 5h14v14',forward:'M4 12h16m-7-7 7 7-7 7',plus:'M12 4v16M4 12h16',close:'m6 6 12 12M18 6 6 18',play:'m9 5 11 7-11 7Z',check:'m5 12 4 4L19 6',bag:'M5 7h14l1 14H4L5 7Zm3 0V5a4 4 0 0 1 8 0v2',down:'M5 9l7 7 7-7'};
export const icon = (name='arrow')=>`<svg class="av-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="${paths[name]||paths.arrow}"/></svg>`;
export const link = (label,href,variant='primary')=>`<a class="av-button av-button--${variant}" href="${escape(href)}"><span>${escape(label)}</span>${icon()}</a>`;
export const button = (label,attrs='',variant='primary')=>`<button class="av-button av-button--${variant}" ${attrs}><span>${escape(label)}</span>${icon('forward')}</button>`;
export const picture = (file,alt,cls='',eager=false)=>`<img class="av-image ${cls}" src="../assets/${escape(file)}" alt="${escape(alt)}" width="1280" height="800" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;
export const eyebrow = text=>`<p class="av-eyebrow">${escape(text)}</p>`;
export const breadcrumb = name=>`<nav class="av-breadcrumb" aria-label="Breadcrumb"><a href="home.html">Home</a><span aria-hidden="true">/</span><span aria-current="page">${escape(name)}</span></nav>`;
export function header(active='') {
 const nav=[['Services','services.html','services'],['Our work','work.html','work'],['The studio','studio.html','studio'],['Shop','shop.html','shop'],['Contact','contact.html','contact']].map(([n,h,id])=>`<a href="${h}" ${active===id?'aria-current="page"':''}>${n}</a>`).join('');
 return `<header class="av-header"><a class="av-brand" href="home.html" aria-label="Auto Vos home"><img src="../assets/auto-vos-logo.svg" alt="Auto Vos" width="1500" height="838"></a><nav class="av-nav" aria-label="Main navigation">${nav}</nav><div class="av-header-actions"><a class="av-bag" href="cart.html" aria-label="Shopping bag">${icon('bag')}<span data-bag-count>0</span></a>${link('Get a quote','quote.html')}<details class="av-mobile-menu"><summary>Menu ${icon('plus')}</summary><nav aria-label="Mobile navigation">${nav}<a href="art.html">Automotive art</a><a href="quote.html">Get a quote</a></nav></details></div></header>`;
}
export function footer(){return `<footer class="av-footer"><div class="av-frame av-footer-grid"><div><a class="av-brand" href="home.html"><img src="../assets/auto-vos-logo.svg" alt="Auto Vos home" width="1500" height="838"></a><p>For the car you love.<br>For the roads ahead.</p></div><div><h2>Visit the studio</h2><address>${business.address}<br>${business.city}</address><a href="https://www.google.com/maps/search/?api=1&amp;query=2130%20Spectra%20Drive%20Colorado%20Springs">Get directions ${icon()}</a></div><div><h2>Let’s talk</h2><a href="tel:${business.tel}">${business.phone}</a><a href="mailto:${business.email}">${business.email}</a><p>${business.hours}<br>Visits by appointment.</p></div><nav aria-label="Footer"><h2>Explore</h2><a href="art.html">Automotive art</a><a href="policy.html">Privacy</a><a href="policy-shipping.html">Shipping & returns</a><a href="../design-system/index.html">Design system</a></nav></div><div class="av-frame av-footer-bottom"><span>© 2026 Auto Vos</span><span>Local rebuild preview · business details pending verification</span><a href="#top">Back to top ↑</a></div></footer>`;}
export function preview(name,controls=''){return `<aside class="av-preview" aria-label="Template preview"><a href="../design-system/index.html#templates">${icon('forward')} Template library</a><span>${escape(name)} · design preview</span>${controls}</aside>`;}
export function layout(title,body,{active='',controls=''}={}) {return `<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="description" content="${escape(title)} — Auto Vos website concept."><title>${escape(title)} | Auto Vos</title><link rel="icon" href="../assets/favicon.svg"><link rel="stylesheet" href="../design-system/tokens.css"><link rel="stylesheet" href="../design-system/system.css"><script src="../design-system/interactions.js" defer></script></head><body id="top" data-demo-price="${product.price}"><a class="av-skip" href="#main">Skip to content</a>${preview(title,controls)}${header(active)}<main id="main" tabindex="-1">${body}</main>${footer()}</body></html>\n`;}
export const intro = (label,title,desc='',extra='')=>`<section class="av-frame av-intro">${breadcrumb(label)}${eyebrow(label)}<h1 class="av-display">${escape(title).replaceAll('\n','<br>')}</h1><div class="av-intro-bottom">${desc?`<p class="av-lead">${escape(desc)}</p>`:''}${extra}</div></section>`;
export const serviceCard = s=>`<article class="av-service-card"><a href="service-${s.id}.html">${picture(s.image,s.alt)}<div class="av-card-heading"><h3>${s.name}</h3>${icon()}</div></a><p>${s.description}</p></article>`;
export const servicesGrid = ()=>`<div class="av-service-grid">${services.map(serviceCard).join('')}</div>`;
export const sectionHeading = (label,title,desc='')=>`<div class="av-section-heading"><div>${eyebrow(label)}<h2 class="av-title">${escape(title)}</h2></div>${desc?`<p>${escape(desc)}</p>`:''}</div>`;
export const faq = (items)=>`<div class="av-faq">${items.map(([q,a])=>`<details><summary>${escape(q)}${icon('plus')}</summary><p>${escape(a)}</p></details>`).join('')}</div>`;
export const invitation = (title='Let’s talk about your car.',desc='Tell us what you drive and what you have in mind.')=>`<section class="av-invitation av-dark"><div class="av-frame"><div>${eyebrow('Your next move')}<h2 class="av-title">${title}</h2><p>${desc}</p></div>${link('Get a quote','quote.html','inverse')}</div></section>`;
export const notice = (title,text,kind='info')=>`<div class="av-notice av-notice--${kind}"><strong>${escape(title)}</strong><p>${escape(text)}</p></div>`;
export const field = (id,label,{type='text',required=false,autocomplete='',help='',options=null,multiline=false}={})=>`<div class="av-field"><label for="${id}">${escape(label)}${required?' <span aria-hidden="true">*</span>':''}</label>${options?`<select id="${id}" name="${id}" ${required?'required':''} aria-describedby="${id}-hint ${id}-error"><option value="">Choose an option</option>${options.map(x=>`<option>${escape(x)}</option>`).join('')}</select>`:multiline?`<textarea id="${id}" name="${id}" rows="4" aria-describedby="${id}-hint ${id}-error"></textarea>`:`<input id="${id}" name="${id}" type="${type}" ${required?'required':''} ${autocomplete?`autocomplete="${autocomplete}"`:''} aria-describedby="${id}-hint ${id}-error">`}<small id="${id}-hint">${escape(help)}</small><p class="av-field-error" id="${id}-error" hidden></p></div>`;
