export const business = {name:'Auto Vos',phone:'720.675.8038',tel:'+17206758038',email:'theautovos@gmail.com',address:'2130 Spectra Drive, Suite 100',city:'Colorado Springs, CO 80904',hours:'Monday–Friday · 9am–6pm'};
export const services = [
 {id:'ppf',name:'Paint protection film',title:'GO AHEAD.\nTAKE THE ROAD.',intro:'A clear layer between your paint and the road ahead.',image:'ppf-installation.webp',alt:'Clear film being fitted to a vehicle’s hood at Auto Vos',description:'Transparent film helps shield painted surfaces from rock chips, light scratches and road debris.',detail:'Focus protection where your car needs it. Talk with the studio about exposed panels, how you drive and the finish you want to preserve.',benefits:[['Road debris','A physical barrier for exposed paint.'],['Coverage that fits','Discuss high-impact areas or full-body coverage.'],['Your finish, visible','A transparent layer that keeps the paint in view.']],faq:[['Does PPF replace ceramic coating?','No. Film provides a physical barrier. Ceramic coating helps with water repellency and cleaning. They address different needs.'],['How much coverage do I need?','Start with how and where you drive. The studio can explain options for your vehicle and priorities.'],['How much does it cost?','Coverage, vehicle shape and preparation affect the quote. Send your vehicle details for a recommendation.']]},
 {id:'ceramic',name:'Ceramic coating',title:'LESS BUILDUP.\nMORE BRILLIANCE.',intro:'A water-repellent layer for the finish you love.',image:'ceramic-application.webp',alt:'A gloved hand applying ceramic coating to blue paint',description:'A protective, water-repellent layer that helps resist contamination and makes your car easier to clean.',detail:'Good preparation comes first. Discuss the condition of your paint, how you care for it and whether coating is the right addition to your protection plan.',benefits:[['Easier cleaning','Helps water and contamination release from the surface.'],['Finish care','Keep regular washing part of the routine.'],['A complement to film','Coating supports maintenance; film addresses physical impacts.']],faq:[['Will coating prevent rock chips?','Ceramic coating does not replace the physical protection of PPF.'],['Can it go over PPF?','Ask the studio about a compatible coating and the appropriate preparation.'],['What maintenance is needed?','The installer will explain washing and care for the specific coating selected.']]},
 {id:'tint',name:'Window tint',title:'KEEP THE VIEW.\nLOSE THE GLARE.',intro:'Comfort for the drive. A finish that feels like your car.',image:'audi-glass.webp',alt:'Glass and bodywork of a blue Audi in the Auto Vos studio',description:'Less glare and infrared heat. More privacy and comfort on your everyday drive.',detail:'Discuss glass coverage, visibility and your preferences with the studio. Film selection should suit the vehicle and applicable requirements.',benefits:[['Daily comfort','Reduce glare and infrared heat.'],['Your preferred look','Compare film options in context.'],['A considered choice','Balance privacy, visibility and your driving needs.']],faq:[['How dark should I go?','Discuss visibility, your preferences and applicable requirements with the installer.'],['Can I tint every window?','Coverage depends on the vehicle and applicable rules. Confirm the scope with the studio.'],['How do I care for new tint?','Follow the installer’s product-specific guidance on drying and cleaning.']]}
];
export const gallery = [
 {id:'yellow',name:'Porsche, in the studio',category:'Cars',image:'porsche-yellow.webp',alt:'Yellow Porsche in the Auto Vos studio',note:'A frame from the Auto Vos shop film.'},
 {id:'film',name:'The fit comes first',category:'Installation',image:'precision-install.webp',alt:'Two technicians fitting film around a vehicle’s bumper',note:'An inside look at paint protection film installation.'},
 {id:'silver',name:'Every line, considered',category:'Cars',image:'porsche-silver.webp',alt:'Silver Porsche in the studio',note:'A frame from the Auto Vos shop film.'},
 {id:'coating',name:'The finishing layer',category:'Installation',image:'ceramic-application.webp',alt:'Ceramic coating applied to blue bodywork',note:'Coating application in the studio.'},
 {id:'918',name:'Porsche 918',category:'Photography',image:'porsche-918.webp',alt:'Porsche 918 photographed with studio lighting',note:'Photography by Caleb Brown; source gallery in the audit snapshot.'},
 {id:'audi',name:'Blue, in detail',category:'Cars',image:'audi-glass.webp',alt:'Blue Audi glass and bodywork',note:'A frame from the Auto Vos shop film.'}
];
export const pageTypes = [
 ['home','Homepage','The complete brand introduction','home.html'],['services','Service overview','Compare protection options','services.html'],['service','Service detail','PPF, coating and tint variants','service-ppf.html'],['work','Work collection','Filter cars, installation and photography','work.html'],['story','Gallery / event story','An image-led story with attribution','story.html'],['studio','Studio & team','Place, people and approach','studio.html'],['art','Creative service','Automotive art and commissioned work','art.html'],['contact','Contact & visit','Direct contact and studio details','contact.html'],['quote','Quote request','A focused inquiry with recovery states','quote.html'],['shop','Shop collection','Merchandise discovery','shop.html'],['product','Product detail','Options, quantity and demo bag','product.html'],['cart','Shopping bag','Editable, empty and recovery states','cart.html'],['checkout','Checkout handoff','Provider boundary and order summary','checkout.html'],['policy','Policy / editorial','Privacy, shipping and returns shells','policy.html'],['confirmation','Confirmation','Request and order state specimens','confirmation.html'],['not-found','Not found','Useful routes back into the site','not-found.html']
];
export const product = {id:'lunar-tee',name:'Lunar GT3RS Tee',category:'Auto Vos apparel',price:35,image:'lunar-tee.webp',description:'An automotive illustration with a lunar setting, from the Auto Vos shop. Product imagery and name are from the audited site; price and options below are demo fixtures.',sizes:['S','M','L','XL']};
export const scenes = [
 ['01','Arrive','I care about this car.','Full-bleed shop imagery and the familiar three-line promise. One quote invitation.','hero-poster.webp','home.html','Static poster first; optional play.'],
 ['02','Understand','What protection do I need?','Three services explained by purpose, using installation photographs.','ppf-installation.webp','services.html','Open a service; keep a direct quote route.'],
 ['03','Compare','What does it actually do?','Benefits, coverage questions and a clear distinction between film and coating.','ceramic-application.webp','service-ppf.html','Native FAQ disclosures; no gated pricing.'],
 ['04','Believe','Show me the work.','A paced collection of real cars and installation details. Credits stay attached.','porsche-yellow.webp','work.html','Filter, reset and open a story.'],
 ['05','Meet','Who will look after it?','Real people and a real place, with verified content required before release.','caleb-brown.webp','studio.html','Contact and directions remain visible.'],
 ['06','Ask','Let’s talk about my car.','A short, labeled form: service, vehicle, contact and context.','audi-glass.webp','quote.html','Keep inputs on error; confirm only real delivery.']
];
